databases:
  - name: mailisearch-rails-render-sample
    databaseName: mailisearch_rails_render_sample
    user: mailisearch_rails_render_sample
    plan: starter
    region: singapore
    postgresMajorVersion: 15

services:
  - type: web
    name: mailisearch-rails-render-sample
    runtime: ruby
    plan: starter
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    initialDeployHook: "./bin/render-initial-deploy.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mailisearch-rails-render-sample
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: MEILISEARCH_URL
        fromService:
          type: web
          name: mailisearch-rails-render-sample-mailisearch
          envVarKey: RENDER_EXTERNAL_URL
      - key: MEILISEARCH_API_KEY
        fromService:
          type: web
          name: mailisearch-rails-render-sample-mailisearch
          envVarKey: MEILI_MASTER_KEY

  - type: web
    name: mailisearch-rails-render-sample-mailisearch
    runtime: docker
    dockerfilePath: ./docker/meilisearch/Dockerfile
    dockerContext: .
    plan: starter
    region: singapore
    disk:
      name: meilisearch-data
      mountPath: /meilisearch-data
      sizeGB: 1
    envVars:
      - key: MEILI_HTTP_ADDR
        value: 0.0.0.0:7700
      - key: MEILI_DB_PATH
        value: /meilisearch-data
      - key: MEILI_MASTER_KEY
        generateValue: true
      - key: MEILI_ENV
        value: production
